"""empty message

Revision ID: 074c5698620d
Revises: aa8d51ae7fc5
Create Date: 2020-12-31 16:51:56.751488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074c5698620d'
down_revision = 'aa8d51ae7fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'time')
    # ### end Alembic commands ###
