"""empty message

Revision ID: 0adf2838dbf3
Revises: bd597b04124e
Create Date: 2020-12-27 15:45:34.492233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0adf2838dbf3'
down_revision = 'bd597b04124e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'color')
    op.drop_column('invoice', 'invoice_id')
    op.drop_column('invoice', 'address')
    op.drop_column('invoice', 'item_num')
    op.drop_column('invoice', 'size')
    op.drop_column('invoice', 'paied')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('paied', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('invoice', sa.Column('size', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('invoice', sa.Column('item_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('invoice', sa.Column('address', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('invoice', sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('invoice', sa.Column('color', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
