"""empty message

Revision ID: 0f30756da3af
Revises: 3e771739f44b
Create Date: 2020-12-31 16:01:25.877542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f30756da3af'
down_revision = '3e771739f44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'p_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('p_address', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
