"""empty message

Revision ID: 3e771739f44b
Revises: d691d98da928
Create Date: 2020-12-31 11:50:17.090256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e771739f44b'
down_revision = 'd691d98da928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('p_address', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'p_address')
    # ### end Alembic commands ###
