"""empty message

Revision ID: 5e943df81bda
Revises: ea7fb094d363
Create Date: 2020-12-28 19:17:45.482284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e943df81bda'
down_revision = 'ea7fb094d363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('item_name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'item_name')
    # ### end Alembic commands ###
