"""empty message

Revision ID: 7dc3de22831d
Revises: 94daef9f0059
Create Date: 2020-12-26 21:27:55.300473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc3de22831d'
down_revision = '94daef9f0059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('color', sa.String(length=10), nullable=False))
    op.add_column('invoice', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('invoice', sa.Column('size', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'size')
    op.drop_column('invoice', 'quantity')
    op.drop_column('invoice', 'color')
    # ### end Alembic commands ###
