"""empty message

Revision ID: 94daef9f0059
Revises: 70a82556f136
Create Date: 2020-12-26 20:48:54.629218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94daef9f0059'
down_revision = '70a82556f136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'name')
    # ### end Alembic commands ###
