"""empty message

Revision ID: 9845d8072a1e
Revises: 7dc3de22831d
Create Date: 2020-12-26 21:32:19.314330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9845d8072a1e'
down_revision = '7dc3de22831d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('paied', sa.Integer(), nullable=False))
    op.drop_column('invoice', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('invoice', 'paied')
    # ### end Alembic commands ###
