"""empty message

Revision ID: 984f54d424ca
Revises: 5e943df81bda
Create Date: 2020-12-29 22:25:51.071047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984f54d424ca'
down_revision = '5e943df81bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buying', sa.Column('card_name', sa.String(length=20), nullable=False))
    op.add_column('buying', sa.Column('card_num', sa.String(length=20), nullable=True))
    op.add_column('buying', sa.Column('payment', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buying', 'payment')
    op.drop_column('buying', 'card_num')
    op.drop_column('buying', 'card_name')
    # ### end Alembic commands ###
