"""empty message

Revision ID: bd597b04124e
Revises: 9845d8072a1e
Create Date: 2020-12-26 21:32:56.620388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd597b04124e'
down_revision = '9845d8072a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'color')
    op.drop_column('item', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('size', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('item', sa.Column('color', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
