"""empty message

Revision ID: d17bc28dac3f
Revises: 18e0b8027018
Create Date: 2020-12-30 16:41:31.096260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17bc28dac3f'
down_revision = '18e0b8027018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buying', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('buying', sa.Column('username', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buying', 'username')
    op.drop_column('buying', 'email')
    # ### end Alembic commands ###
