"""empty message

Revision ID: ea7fb094d363
Revises: 0adf2838dbf3
Create Date: 2020-12-27 21:54:58.559759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea7fb094d363'
down_revision = '0adf2838dbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('address', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
